### PR TITLE
Mastery Exercise Submission

### PR DESCRIPTION
**Pull request by laurensaurenson**

### CODE REVIEW

**Comment by laurensaurenson** [comment]
@morecallan Maybe mvp?

**Comment by morecallan** [comment]
Looking great. Nice ES6 usage and succinct code. Kudos on naming convention, too. 

There are a few little things I am going to ask before you merge:
-Comments! (At the very least, put the quiz requirements in as comments where relevant)
-You actually don't need to print a usage statement if the user has a valid command.

**Comment by laurensaurenson** [comment]
@morecallan Thanks! I wasn't sure on the usage statement. I went back and tried to comment everything though.

**Comment by morecallan** [comment]
@laurensaurenson Almost there. I'd actually edit your comments which a little clarification: split() isn't making it into an array exactly. It has similar outcome, but take a look at the docs just to clarify in your comments how it is affecting the stream (_wink/hint_).

**Comment by laurensaurenson** [comment]
@morecallan Ok, I changed the wording on that comment.

**Comment by morecallan** [comment]
👍 you're good to merge. 

note: what the split() is doing is breaking the **stream** up into chunks by line, so each chunk to go into the next transform steam (in this case map) is an individual line. Cool, eh? 

now merge!

**Pull request merged**
